database:
  url: "postgres://meatball:admin1234@postgres:5432/meatball?sslmode=disable"
api:
  port: 3000
  enable_cors: true
log:
  level: "debug"
eureka:
  gateway:
    url: "http://0.0.0.0:port/eureka"
  instance:
    id: "instance-id"
    app: "cookerserver"
    hostname: "0.0.0.0"
    ipaddress: "0.0.0.0"
    port: 3000
    ttl: 30
static:
  path: "static"
