version: "3.6"

services:
  postgres:
    image: postgres:latest
    volumes:
      - "db-data:/var/lib/postgres/data"
    ports:
      - 20000:5432
    environment:
      POSTGRES_DB: "cookerserver"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "meatballa1234"

  cookerserver:
    build:
      context: .
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./config.prod.yml:/usr/app/config.yml
      - web-data:/usr/app/static

volumes:
  db-data:
  web-data:

