version: "3.6"

services:
  postgres:
    image: postgres:latest
    volumes:
      - "db-data:/var/lib/postgres/data"
    ports:
      - 20000:5432
    environment:
      POSTGRES_DB: cooker
      POSTGRES_USER: cooker
      POSTGRES_PASSWORD: admin1234

  app: 
    build: 
      context: .
      dockerfile: dev.Dockerfile
    restart: on-failure
    volumes:
    - ./cmd:/src/cmd
    - ./internal:/src/internal
    - ./static:/src/static
    - app-go-pkg:/go/pkg
    ports:
    - 3000:3000
    command:
    - -c
    - .air.toml
    env_file:
    - dev.env
    depends_on:
    - postgres

volumes:
  app-go-pkg:
  db-data:
